clc,clear;
%设定求解区域
xy_range=[0,1,0,1];
%设定差分网格
Nxy=[41,41];
%设定方程参数
equ_para.c=@(x,y)1;
equ_para.a=@(x,y)0;
equ_para.f=@(x,y)1;
%设定边界条件
bc_type=[1,1,1,1];
bc_para.h_left=@(x,y)1;
bc_para.r_left=@(x,y)0;
bc_para.h_right=@(x,y)1;
bc_para.r_right=@(x,y)0;
bc_para.h_bottom=@(x,y)1;
bc_para.r_bottom=@(x,y)0;
bc_para.h_top=@(x,y)1;
bc_para.r_top=@(x,y)0;
%设定求解方法
method='fivepoint';
solve_elliptic(xy_range,Nxy,equ_para,bc_type,bc_para,method)