clc,clear;
%设定求解区域
xyt_range=[0,0.5,0,0.5,0,0.1];
%设定差分网格点数
Nxyt=[100,100,100];
%设定方程参数
equ_para.d_in=1;
equ_para.d_ma=1;
equ_para.c_in=1;
equ_para.c_ma=100;
equ_para.f=@(x,y,t)1;
equ_para.len=0.02;
equ_para.epsilon=0.1;
%设定初始条件
u0=@(x,y)0;
%设定边界条件
bc_type=[1,1,1,1];
bc_para.h_left=@(x,y,t)1;
bc_para.r_left=@(x,y,t)0;
bc_para.h_right=@(x,y,t)1;
bc_para.r_right=@(x,y,t)0;
bc_para.h_top=@(x,y,t)1;
bc_para.r_top=@(x,y,t)0;
bc_para.h_bottom=@(x,y,t)1;
bc_para.r_bottom=@(x,y,t)0;
solve_mulpar_dir(xyt_range,Nxyt,equ_para,u0,bc_type,bc_para)