clc,clear;
%设定求解区域
xy_range=[0,1,0,1];
%设定差分网格
Nxy=[100,100];
%设定方程参数
equ_para.c_in=1;
equ_para.c_ma=100;
equ_para.epsilon=0.1;
equ_para.f=@(x,y)10;
equ_para.len=0.03;
%设定边界条件
bc_type=[1,1,1,1];
bc_para.h_left=@(x,y)1;
bc_para.r_left=@(x,y)0;
bc_para.h_right=@(x,y)1;
bc_para.r_right=@(x,y)0;
bc_para.h_bottom=@(x,y)1;
bc_para.r_bottom=@(x,y)0;
bc_para.h_top=@(x,y)1;
bc_para.r_top=@(x,y)0;
%设定求解方法
method='fivepoint';
solve_mulell_dir(xy_range,Nxy,equ_para,bc_type,bc_para,method)